spring:
  datasource:
    url: jdbc:postgresql://loclhost:5432/kanban
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            nn_contextual_creation: true

      hibernate:
        ddl-auto: create-drop